### PR TITLE
Hunter 3.30.1 Add CMake files / Update version

### PR DESCRIPTION
**Pull request by kaihowl**
This is a reapplication of the original CMake files to a clean version of the CMake 3.30.1 amalgamation. The only difference is the version increase in the CMakeLists.txt

### CODE REVIEW

**Comment by kaihowl** [comment]
@rbsheth Please have a look. A local test of this worked just fine, i.e., tar.gz-ed the files up with `git-archive`, added a new version to the hunter packages and ran it locally. After merging this, we could create a new release and do the actual increase of the version in hunter.

**Comment by kaihowl** [comment]
Also please note that I pushed the branch `hunter-3.30.1-cmake` and wanted to add the version change on top. As the branches are automatically write protected, I was not able to do so. Can you please clean up that branch? Apologies for that mess.

**Comment by rbsheth** [comment]
@kaihowl I'm a bit confused - did you want to merge this into `hunter-3.30.1-cmake`? Or is this a standalone branch? I also see `hunter-3.30.1`. Let me know what you want to merge and keep and I'll do it.

**Comment by kaihowl** [comment]
> Also please note that I pushed the branch `hunter-3.30.1-cmake` and wanted to add the version change on top. As the branches are automatically write protected, I was not able to do so. Can you please clean up that branch? Apologies for that mess.

This comment might be have been confusing. In simpler words: The branch `hunter-3.30.1-cmake` can be deleted entirely. The branch `hunter-3.30.1-cmake2` should be merged into `hunter-3.30.1`. Afterwards, `hunter-3.30.1` should be released.

What did I do? I followed the prior art on this fork and https://docs.hunter.sh/en/latest/creating-new/patch.html. I checked out [sqlite/sqlite](https://github.com/sqlite/sqlite/) on the tag `version-3.30.1`, ran `mkdir build && cd build && ../configure && make sqlite3.c`. The resulting files for `shell.c`, `sqlite3.c`, `sqlite3.h`, and `sqlite3ext.h` were added to the branch `hunter-3.30.1`. This branch was created with `--orphan` and does not share history with other branches. Compared to the original description in the docs of how to patch sources, this is a little uncommon as it checks in artifacts of a build instead of just basing commits on top of a tag from the upstream repo. Yet, this is how it was done before as far as I can see and it does make sense in order to keep the amalgamation in a simple way.

Based on the clean branch `version-3.30.1` I created `hunter-3.30.1-cmake2`. This branch cherry picks the cmake files that were applied to other branches and only changes the version number. This was not simply pushed to the branch as the docs and [this prior PR](https://github.com/hunter-packages/sqlite3/pull/2) suggest giving others the opportunity to review.

I hope I understood the question correct and did not reiterate things you already know.

**Comment by rbsheth** [comment]
@kaihowl Thanks for the explanation. Merged your `cmake2` branch into `hunter-3.30.1` and made a release here: https://github.com/cpp-pm/sqlite3/releases/tag/v3.30.1-p0

**Pull request merged**
